############################################################
# +------------------------------------------------------+ #
# |                Database Configuration                | #
# +------------------------------------------------------+ #
############################################################

database:
  mysql:
    host: "localhost"
    port: 3306
    database: "staffshifts"
    username: "root"
    password: "password"
